### ISSUE TITLE
Create extraction model

### ISSUE THREAD

**Issue by AlekseiMart** [cs130-w22/Group-B3#2]
## Epic
Isolate images and text from the given document.

## User Stories
- [x] Get Training/Test sets
- [x] Preprocess image: delete text, keep borders of images
- [x] Extract each individual piece
- [x] Send them to the interpretation model
- [x] Create CNN to extract feature maps
- [x] Create Region Proposal Layer On top of CNN
