### ISSUE TITLE
Integrate Backend to Frontend

### ISSUE THREAD

**Issue by DayuenKim** [cs130-w22/Group-B3#3]
## Epic
Create Back end to handle requests from Front end

## User Stories
- [x] Obtain http request from Front end
- [x] Read images from compressed files
- [x] Delete or ignore non-image files
- [x] Compile cropped images into a compressed file
- [x] #12
